export const DEVTOOL_RUNTIME_CONNECTION_PORT = "DevtoolPort"
export const CONTENT_SCRIPT_RUNTIME_CONNECTION_PORT = "ContentScriptPort"
export const VOID_ELEMENTS = [
  "area",
  "base",
  "br",
  "col",
  "embed",
  "hr",
  "img",
  "input",
  "link",
  "meta",
  "param",
  "source",
  "track",
  "wbr",
]

// always keep this in alphabetical order
export const PSEUDO_ELEMENTS = [
  "after",
  "backdrop",
  "before",
  "cue",
  "cure-region",
  "first-letter",
  "first-line",
  "file-selector-button",
  "grammar-error",
  "marker",
  "part()",
  "placeholder",
  "selection",
  "slotted()",
  "spelling-error",
  "target-text",
]

// always keep this in alphabetical order
export const PSEUDO_CLASSES = [
  "active",
  "any-link",
  "checked",
  "default",
  "defined",
  "dir()",
  "disabled",
  "empty",
  "enabled",
  "first",
  "first-child",
  "first-of-type",
  "fullscreen",
  "focus",
  "focus-visible",
  "focus-within",
  "host",
  "hover",
  "indeterminate",
  "in-range",
  "invalid",
  "lang()",
  "last-child",
  "last-of-type",
  "left",
  "link",
  "not()",
  "nth-child()",
  "nth-last-child()",
  "nth-last-of-type()",
  "nth-of-type()",
  "only-child",
  "only-of-type",
  "optional",
  "out-of-range",
  "placeholder-shown",
  "read-only",
  "read-write",
  "required",
  "right",
  "root",
  "scope",
  "state()",
  "target",
  "valid",
  "visited",
]
